Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "nginx"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "NginxTest"
    end

    config.vm.network "private_network", ip: "192.168.33.50"
    config.vm.synced_folder "./template", "/var/www/html"

    config.vm.provision "shell", path: "./scripts/install-nginx.sh"
end
