Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "nginx-dev"

  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.synced_folder "./scripts", "/home/vagrant/scripts"
  # config.vm.provision "shell", path: "bootstrap.sh"
end
